apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-conf
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  nginx;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /api {
                rewrite ^/api(/.*)$ $1 break;                # /api 제거
                proxy_pass http://backend-svc:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
    }