apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kms
  name: frontend-deployment-edulink
spec:
  selector:
    matchLabels:
      type: frontend
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
      - name: frontend
        image: mstar228/edulink-frontend:latest
        ports:
          - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /etc/nginx/conf.d/
      volumes:
        - name: config
          configMap:
            name: frontend-conf
