- name: MongoDB Replica Set Setup
  hosts: ansible_cluster
  become: yes
  vars:
    mongo_version: "6.0"
    mongo_user: "admin"
    mongo_password: "qwer1234"
    replica_set_name: "rs0"
    bind_ip: "0.0.0.0"

  tasks:
    - name: Add MongoDB APT repository key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-{{ mongo_version }}.asc
        state: present

    - name: Add MongoDB APT repository
      apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/{{ mongo_version }} multiverse"
        state: present
        filename: mongodb-org

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Overwrite mongod.conf with replica set configuration
      copy:
        dest: /etc/mongod.conf
        content: |
          storage:
            dbPath: /var/lib/mongodb
            journal:
              enabled: true
          systemLog:
            destination: file
            logAppend: true
            path: /var/log/mongodb/mongod.log
          net:
            bindIp: {{ bind_ip }}
            port: 27017
          replication:
            replSetName: {{ replica_set_name }}
      notify: Restart MongoDB

    - name: Ensure mongod is enabled and started
      systemd:
        name: mongod
        enabled: yes
        state: started

  handlers:
    - name: Restart MongoDB
      systemd:
        name: mongod
        state: restarted
